### ISSUE TITLE
Commands from the discord don't propagate to Minecraft.

### ISSUE THREAD

**Issue by BluSunrize** [MiraWaNeko/DiscordIntegration#1]
At least the /kick one doesn't.
Would be nice to have that, except that a check for permissions would be required.
Now with Discord and MC names possibly differing, comparing against those might not be viable.
Is there a way do detect the roles of a discord user and possibly have a string array in the config of roles that equate to OP permissions on the server?
Alternatively, a config on specific discord user names that are allowed those permissions.

**Comment by MiraWaNeko** [comment]
Roles would definitely be possible as that's what's used for commands in the config file (As seen on the [Config Explaination](https://github.com/Chikachi/ChikachiDiscord/wiki/Config-Explaination) wiki page)

**Comment by MiraWaNeko** [comment]
I'd rather not use `/` as the beginning character as this could conflict with Discord's own commands.

A possible solution could be to add the ability to add custom commands in the config file.

Example

``` json
"commands": {
    "custom": [{
        "name": "kick",
        "cmd": "/kick $1",
        "roles": ["MyAdminRoleOnDiscord", "MyServerModeratorRoleOnDiscord"]
    }]
}
```

That would add `!kick` as a command on the Discord bot that can only be executed by people in two roles. When used as `!kick Steve` it would execute `/kick Steve` on the server.

**Comment by MiraWaNeko** [comment]
Implemented as custom commands - Read more about it on [this wiki page](https://github.com/Chikachi/ChikachiDiscord/wiki/Custom-Commands)
