### ISSUE TITLE
[Suggestion] association pseudo discord <=> pseudo minecraft  

### ISSUE THREAD

**Issue by andrelec1** [MiraWaNeko/DiscordIntegration#100]
It would be nice if we can list somewhere all speudo minecraft with clientID discord 

use minecraft speudo on minecraft  / translate pseudo minecraft with discord pseudo on discord ...

**Comment by MiraWaNeko** [comment]
I'm guessing you mean using the linked accounts?

**Comment by andrelec1** [comment]
maybe ^^ 

juste when someone type @XXX in discord , detecte and replace this by minecraft pseudo ( if the id is in the list ) , and vice versa ( but i think detect pseudo in minecraft is bit more difficult ^^ )
