### ISSUE TITLE
[Suggestion] Link img in minecraft when send img on discord

### ISSUE THREAD

**Issue by andrelec1** [MiraWaNeko/DiscordIntegration#104]
If some one send pick in discord, the mod display blank message in minecraft ...

Can you send the url of the file ? ( cdn.discord.com )

**Comment by Inrixia** [comment]
It would also be nice if links that are sent on discord are actually clickable in MC. As currently they only relay the text and don't let people click it ingame.

**Comment by jusvit** [comment]
#171
