### ISSUE TITLE
Discord bot only relaying messages one way

### ISSUE THREAD

**Issue by neogeo0823** [MiraWaNeko/DiscordIntegration#108]
### Base informations
**Minecraft version: 1.10.2

**DiscordIntegration version: 3.0.4

**Link to pastebin with (censored) config: https://pastebin.com/bHfMmrae

### Expected behavior
Discord bot should relay chat between Discord channel and minecraft server

### Actual behavior
Discord bot relays chat from server to channel, but not channel to server. This has been happening for around a month now, and began happening while we were still on version 2.1.0 of the mod. We updated to the latest version(3.0.4) today and it did not fix the problem.

### Steps to reproduce
Install and configure bot as normal. We do not know what specifically produces this behavior, as we have not been able to get the chat to relay correctly. My currently running theory is improperly formatted chat going to the MC server, which is thus not being accepted and displayed.

**Comment by MiraWaNeko** [comment]
Add the channel to the channels object under Discord.

Like shown on the wiki
![image](https://user-images.githubusercontent.com/10409177/31577710-d9f54e0c-b113-11e7-9ce4-244a07e66c60.png)

**Comment by neogeo0823** [comment]
Do you have a link to the wiki page that shows that? Because that's not shown on the wiki as linked through this github. There's a link to the method for getting the chatbot set up and getting the channel token(which seems out of date, btw), but it never shows anything from the config. The link to the explanation for the config is a dead link that leads nowhere. 

EDIT: Nevermind, I'm dumb and forgot the links on the side of the page that point to the actual page. the one link in the middle seems to be misspelled and therefore broken.

**Comment by neogeo0823** [comment]
here's a pastebin to my latest attempt at getting this to work: https://pastebin.com/LrsPF1Jf 

Something is wrong syntax-wise, as the bot won't even load up when the server starts now. I snipped the channel ID for discord, but it's only connecting to one channel, if that matters. We basically just use it to relay chat between that channel and the server, and we like to use the !online command to see who's on the server before we log in. What am I doing wrong here and how do I fix it?

**Comment by Gunner76th** [comment]
Found the solution to the problem. You forgot to also put the channel ID in line 44 on your pastbin post. If you take a look here https://pastebin.com/cdxecp4u and replace the %Token-ID% and %Channel-ID% with your own personal values it will work. Please note, there are 2 (Two) spots where you need to enter the Channel ID. If you use JSONLint.com to validate your json, they are at lines 20 and 41 on my pastebin. Your personal line numbers might be different if you have custom commands and such entered.

**Comment by neogeo0823** [comment]
holy crap, that worked! Thank you so much, my users can now actually talk back and forth on the server again!

**Comment by Gunner76th** [comment]
You are welcome, also please note that the copy of the config I posted does not have ANY commands in it, so you would need to add all of the basic ones that are usually in the config by default, as well as any custom commands that you want to use.
