### ISSUE TITLE
[Suggestion] Emoji to plaintext

### ISSUE THREAD

**Issue by Mohron** [MiraWaNeko/DiscordIntegration#11]
When discord converts plain text emoticons to Emoji they do not send to the MC server. My suggestion is automatically change `:smile:`  to :) and vice versa to allow the best to way compatibility.

Example List:
https://github.com/nguyenquyhy/Sponge-Discord/blob/7935a01a455876bd7f992fec6570f2c4c9c9d369/EMOJI.md

**Comment by MiraWaNeko** [comment]
Added in 1.4.0
