### ISSUE TITLE
Discord Integration not using bot nick names.

### ISSUE THREAD

**Issue by jc2xs** [MiraWaNeko/DiscordIntegration#114]
Discord version is 3.0.4 for 1.7.10 and 1.12.2.  I have configured discord integration on several server to the same discord channel.  And I've re-used bots by changing their nickname in discord integration and renaming them in the discord web app used to manage the bots.  However, I noticed that in game the original bot names is used instead of the nickname. that it is in discord.  I did this to save some time and re-use bots instead of creating new ones and deleting old one.

So this might be more a feature request rather than an actual bug.

**Comment by andrelec1** [comment]
i think this issus is link with : https://github.com/Chikachi/DiscordIntegration/issues/101

**Comment by jc2xs** [comment]
Yep..  I believe you are correct.  I didn't catch that was the same issue.
