### ISSUE TITLE
[Suggestion] Option for different roles on discord to have different colours in MC chat

### ISSUE THREAD

**Issue by SpookyFence** [MiraWaNeko/DiscordIntegration#117]

**Comment by Mijago** [comment]
Well, implementing the default colors should not be that difficult. 
But how to find the color to be used for custom colors (as one can select any color for discord roles)?

We could use something like [this](https://codereview.stackexchange.com/questions/115046/fast-way-to-find-the-most-similar-color-in-an-array?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa) to find the nearest color  (the palette would hold every Minecraft color and return the MC-colorcode of it) and then add the color to the argument list as {USERCOLOR} or something similar.

**Comment by Mijago** [comment]
I tested it with RGB color space, works often, but mixes some colors up (as they may be closer together for the computer, but not for the human eye).

To do this correctly, we need to use a different color space than RGB.
CIELAB would suffice, i guess, but I do not think adding it only for this feature is worth it. 

Any input or other ideas?
