### ISSUE TITLE
1710 - Cfg doesn't seem to work

### ISSUE THREAD

**Issue by cauliflower69** [MiraWaNeko/DiscordIntegration#12]
We have disabled the achievements etc and they are being sent to the discord group. Also server start and shutdown are enabled and not being shown

http://imgur.com/4MhGzGA

{"discord":{"token":"REMOVED","channel":"REMOVED","commands":{"online":{"enabled":true,"roles":[],"aliases":[]},"tps":{"enabled":true,"roles":[],"aliases":[],"colored":false},"unstuck":{"enabled":true,"roles":[admin],"aliases":[]},"custom":[]}},"messages":{"discord":{"chat":{"enabled":true,"message":"<**%USER%**> %MESSAGE%","relaySayCommand":false},"death":{"enabled":false,"message":"**%USER%** %MESSAGE%"},"achievement":{"enabled":false,"message":"Congrats to **%USER%** for earning the achievement **%ACHIEVEMENT%** (%DESCRIPTION%)"},"join":{"enabled":false,"message":"**%USER%** has joined the server!"},"leave":{"enabled":false,"message":"**%USER%** left the server!"},"startup":{"enabled":true,"message":"**Server started**"},"shutdown":{"enabled":true,"message":"**Server shutdown**"}},"minecraft":{"chat":{"enabled":true,"message":"<**%USER%**> %MESSAGE%","maxLength":-1,"usernameColor":"red"}}},"experimental":{"fakePlayers":false}}

**Comment by MiraWaNeko** [comment]
It's working fine for me - possibly try restarting the server

**Comment by cauliflower69** [comment]
I have updated the cfg and it works now
