### ISSUE TITLE
[Idea] Nucleus Nickname Support

### ISSUE THREAD

**Issue by 132ikl** [MiraWaNeko/DiscordIntegration#120]
We run a Sponge server with the plugin Nucleus installed, which allows for in-game nicknames. It would be nice for these nicknames to go to Discord as well. While it could techincially be implemented using Sponge and Nucleus's API, it seems like a bad idea to combine a Forge mod with Sponge. All of the nicknames are stored in files, so they should be easily accessible, it would just be a little "hackish". The nickname file only updates on restart so it shouldn't be too difficult to manage and still remains useful on most servers where with consistent restarts. If you approve of the idea I can do the work for it. This could also be fairly easily expanded to other plugins/mods that provided nicknames if any are suggested in the future.

**Comment by MiraWaNeko** [comment]
✔️
