### ISSUE TITLE
Jenkins not building

### ISSUE THREAD

**Issue by 132ikl** [MiraWaNeko/DiscordIntegration#121]
Jenkins isn't submitting after the PR I submitted, although it doesn't seem to have anything to do with the PR itself. Not sure what's happening here.

https://build.chikachi.net/blue/organizations/jenkins/Chikachi%2FDiscordIntegration/detail/1.12/15/pipeline

**Comment by MiraWaNeko** [comment]
It's not the first time that part of the build pipeline have failed.
Not sure why it's happening, but rebuilding worked fine.
