### ISSUE TITLE
No achievements (advancements) being relayed to discord

### ISSUE THREAD

**Issue by Ricket** [MiraWaNeko/DiscordIntegration#126]
### Base informations
**Minecraft version:** 1.12.2

**Modpack:** FTB Revelation 1.3.0

**DiscordIntegration version:** DiscordIntegration-mc1.12.2-3.0.4.jar

**Link to pastebin with (censored) config:** https://pastebin.com/4C8GRYUq

### Expected behavior
Advancements should be relayed to discord

### Actual behavior
No advancements since the start of our server have been sent to our discord channel. We have gained various advancements and have also had lots of chat messages, logins/outs, and deaths that have successfully been relayed. `relayAchievements` is set to true (see the pastebin'd config).

**Comment by Ricket** [comment]
Huh, looks like it's just totally commented out, probably due to "achievement"->"advancement": https://github.com/Chikachi/DiscordIntegration/blob/f0686253ab710fdb458ab2b91f0725f8265a3f1a/src/main/java/chikachi/discord/listener/MinecraftListener.java#L261-L318

**Comment by MiraWaNeko** [comment]
There were no event for advancements at the time that code got written.

**Comment by Ricket** [comment]
Thanks for the quick fix :+1:

**Comment by Ricket** [comment]
I built the mod and verified your fix. Only thing is the config file still references "achievements". You may want to rename those keys and messages.

**Comment by Muzarmo** [comment]
Hi! Is this fix being integrated into a new version? 

Kind regards

**Comment by MiraWaNeko** [comment]
3.0.5 released with the fix
