### ISSUE TITLE
Installation Instructions?

### ISSUE THREAD

**Issue by officiallymarky** [MiraWaNeko/DiscordIntegration#130]
### Base informations
**Minecraft version:**
1.12.2

**DiscordIntegration version:**
Latest 

**Link to pastebin with (censored) config:** *Optional*

### Expected behavior
jar file for installation

### Actual behavior
no jar file for installation or instructions

### Steps to reproduce
visited github, liked it, went to install, no jar file for installation, looked for instructions, no instructions, (╯°□°）╯︵ ┻━┻

**Comment by Ricket** [comment]
Click the url on the top of the project page to go to discordintegration.net:

![image](https://user-images.githubusercontent.com/196978/36344788-09a95b3c-13e5-11e8-9ee2-09c400fd06ca.png)

That redirects you to the curseforge page. Click the Files tab.

![image](https://user-images.githubusercontent.com/196978/36344792-1d336c9c-13e5-11e8-84eb-2c1fff885bbd.png)

Download the appropriate jar file for your version of minecraft.

![image](https://user-images.githubusercontent.com/196978/36344796-30c5f22a-13e5-11e8-95bc-3ce97384beec.png)

**Comment by officiallymarky** [comment]
Haha, thanks!
