### ISSUE TITLE
Chat Messages Not Being Relayed To Discord

### ISSUE THREAD

**Issue by ChloeDawn** [MiraWaNeko/DiscordIntegration#131]
Everything seems to be relayed from Minecraft -> Discord except for actual chat messages. I'm not sure if I have set something up incorrectly, but I have triple checked my config and it seems fine. Chat messages don't seem to be displaying on my server console either.

**DiscordIntegration version:** [1.12.2-3.0.4](https://minecraft.curseforge.com/projects/discordintegration/files/2488480)
**Forge version:** [1.12.2-14.23.2.2624](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.2.2624/forge-1.12.2-14.23.2.2624-changelog.txt)
**Configuration:** [gist:discordintegration.json](https://gist.github.com/InsomniaKitten/8cbf11afa3c074a357b59f53f05f2535)

**Comment by ChloeDawn** [comment]
I have found the source of the issue. I forgot I had a Charset tweak enabled which mutes chat based on distance from the player. The relevant code can be seen below:

 [pl.asie.charset.module.tweak.chat.CharsetTweakChat.java#L140-L144](https://github.com/CharsetMC/Charset/blob/1.12/src/main/java/pl/asie/charset/module/tweak/chat/CharsetTweakChat.java#L140-L144)

The solution would be to use `EventPriority#LOW` at [MinecraftListener.java#L215](https://github.com/Chikachi/DiscordIntegration/blob/1.12/src/main/java/chikachi/discord/listener/MinecraftListener.java#L215), and in turn, @asiekierka should be using `EventPriority#LOWEST` to ensure monitoring and distance culling of messages occurs after any potential modification to the message component has occurred - which is an ideal change regardless of this issue.

**Comment by asiekierka** [comment]
What's the point of using distance-based chat if you're just relaying everything to ~~a botn~~Discord?

It would be better for me to be able to somehow relay those messages which are not distance-based ("shout" messages) to DiscordIntegration, and back.

**Comment by MiraWaNeko** [comment]
Yeah, it doesn't make much sense for distance-based chat.
DiscordIntegration supports [IMC messages](https://github.com/Chikachi/DiscordIntegration/wiki/IMC-Feature) to allow for sending/receiving Discord messages.

**Comment by asiekierka** [comment]
>sendRuntimeMessage

Well, that's something I've never heard of. Hm! I might end up supporting this.

**Comment by ghost** [comment]
Hi, I am running sky factory 4 and I noticed that this same charset mod is included the pack. I have never used or heard of it so how do I disable the localchat distance think without breaking the modpack?
