### ISSUE TITLE
Add ability to update minecraft channel description

### ISSUE THREAD

**Issue by Sirse** [MiraWaNeko/DiscordIntegration#134]
Suggestion: Add ability to update Discord channel description as custom text with placeholders like (players count, tps, unique players count, uptime, etc).

**Comment by Mijago** [comment]
How often would you suggest it should be updated?  
Automatically or on command execution?

**Comment by Sirse** [comment]
Automatically, i think. Once at 5 minutes, e.g.

**Comment by Mijago** [comment]
What's the difference between "player count" and "unique player count"?

**Comment by Sirse** [comment]
Player count - current count of player on the server
Unique players count - the total amount of players, who visited a server during all time
