### ISSUE TITLE
do you have permission support

### ISSUE THREAD

**Issue by REVIEWGAMINGMAN** [MiraWaNeko/DiscordIntegration#135]
### Base informations
**Minecraft version:**
1.7.10
**DiscordIntegration version:**
DiscordIntegration-mc1.7.10-3.0.5.jar

do you have permission support

**Comment by MiraWaNeko** [comment]
What do you mean?

**Comment by REVIEWGAMINGMAN** [comment]
like GroupManager or pex

**Comment by MiraWaNeko** [comment]
Not at the current time.
The only permission wise is that Minecraft commands require OP.

**Comment by REVIEWGAMINGMAN** [comment]
ok thanks
