### ISSUE TITLE
[suggestion] use webhook to relay player messages

### ISSUE THREAD

**Issue by RCXcrafter** [MiraWaNeko/DiscordIntegration#136]
Instead of having the bot itself post messages from ingame players you can use a discord webhook for this. It would look something like this: https://forum.fivem.net/uploads/default/original/2X/a/a04827d09f137276d066750e0c99a3ef99bc121f.png
Aditionally you can get an image of the player's face from https://www.cravatar.eu to add to the message. (getting the image with the player name doesn't seem to work for most players but it works fine with the uuid)

**Comment by MiraWaNeko** [comment]
Already implemented, look for webhook in [the configuration explanation](https://wiki.discordintegration.net/Config-Explanation-v3)

**Comment by RCXcrafter** [comment]
Oh whoops, I didn't notice that for some reason. Thanks for already having my suggestion implemented.
