### ISSUE TITLE
commands results to "Unknown command"

### ISSUE THREAD

**Issue by Cronosus** [MiraWaNeko/DiscordIntegration#137]
### Base informations
**Minecraft version:**
1.7.10

**DiscordIntegration version:**
3.0.5

**Link to pastebin with (censored) config:** *Optional*
http://pasted.co/f3751800

### Expected behavior
executed command
### Actual behavior
any nondiscord command return
"Unknown command. Try /help for a list of commands"
i think ist caused by / in command, console commands working without slash and if you add /,then in cosole have same result
only commands with "discord .." working, but any custom command, not even default commands showed in example config v3, not working
### Steps to reproduce
just add any command

**Comment by Cronosus** [comment]
just little ad. messages with playerJoin, playerLeft and playerDeath not working

**Comment by Ricket** [comment]
Your config has restart, tps, online, kick. Which of these doesn't work? Looks like restart has a typo, "astop" instead of "stop".

When player joins or leaves, is there any error in the server console?

**Comment by Cronosus** [comment]
restart and kick and any other i tried to add
and yes, we have astop instead of stop (its timed stopping)
and no errors with messages, in discord is typed default message in english, i dont know where is problem, maybe is this playerJoin, playerLeft and playerDeath not correct

when i type in console just "astop" then its normally executed, but when i rype "/astop" then i have this exact error "Unknown command. Try /help for a list of commands"
then i think its caused by slash "/" added by mod to command

**Comment by Cronosus** [comment]
and no errors with messages, in discord is typed default message in english

**Comment by Cronosus** [comment]
as i say, i think its caused by slash "/"
when i type in console just "astop" then its normally executed, but when i rype "/astop" then i have this exact error "Unknown command. Try /help for a list of commands"

**Comment by Mijago** [comment]
These commands are for use in Discord only, so using them in game has no effect as the game does not know about them.
Your "astop" has to be used in Discord as "!astop".

**Comment by Mijago** [comment]
In your configuration you use commandPrefix "!" but you want to issue the commands with "/", so i think you are trying to execute the commands ingame. These commands are for use in Discord only, the game itself does not know about them, hence the message.


* Also note that canExecuteCommands is set to false in your configuration, so make sure you enable it in your channel settings

**Comment by Cronosus** [comment]
i mean discord->minecraft commands
and i tried with true and with false.. still have this "Unknown command. Try /help for a list of commands"
discord tried to use command configured, but i think it uses wrong prefix or something
problem is not "it cant use command" but problem is "it uses wrong command"

**Comment by Mijago** [comment]
I will have a look into this as soon as I port the v4 changes into the 1.7.10 branch.
