### ISSUE TITLE
[Suggestion] Integrate with DynmapForge

### ISSUE THREAD

**Issue by redsgreens** [MiraWaNeko/DiscordIntegration#14]
Integration with DynmapForge would be nice, so that messages from Discord would show up in the Dynmap chat and vice-versa. An example of a similar type of mod that does this is EiraIRC (an IRC<->Minecraft bridge). We use the Dynmap for mapping purposes but it is also nice because guests can chat from there without logging in or signing up for anything.

**Comment by redsgreens** [comment]
Does this mean that the enhancement was added? I'm just excited, thanks for your great work.

**Comment by MiraWaNeko** [comment]
It's in the current alpha of v3

You can download it to try it out over at https://build.discordintegration.net/job/v3/lastSuccessfulBuild/

https://github.com/Chikachi/DiscordIntegration/blob/v3/src/main/java/chikachi/discord/integration/DynmapIntegration.java

**Comment by redsgreens** [comment]
Wow, that's great. Thank you!
