### ISSUE TITLE
Commands in Discord does not work. Even from demo config.

### ISSUE THREAD

**Issue by Pirog17000** [MiraWaNeko/DiscordIntegration#144]
### Base informations
**Minecraft version:** 1.12.2

**DiscordIntegration version:** mc1.12.2-3.0.5

**Server type and version:** *Forge*

**Link to pastebin with (censored) config:** *Optional*
https://pastebin.com/PGpjg3NB  (token and IDs are randoms)

### Expected behavior
Working commands, at least !tps , !online, !list
### Actual behavior
Not working commands. None of them.
### Steps to reproduce
Well, config is all you need.

Also, if I put the exact demo configuration with my IDs and without comments into JSON parser, it does show the error after permission roles for the first command.

**Comment by Sirse** [comment]
Change
`    "channels": {
      "maturin": {`
to
`    "channels": {
      "generic": {`
