### ISSUE TITLE
Time calculation bug

### ISSUE THREAD

**Issue by Sirse** [MiraWaNeko/DiscordIntegration#145]
### Base informations
**Minecraft version:**
1.7.10
**DiscordIntegration version:**
3.0.5
**Server type and version:** *Forge/Spigot/Sponge*
Forge

Then i type discord uptime in console i'm getting next timestamp (-54 hours):

![image](https://user-images.githubusercontent.com/3335371/39817611-ca8d692e-53c8-11e8-9320-7746cb0e4ece.png)

**Comment by Mijago** [comment]
https://github.com/Chikachi/DiscordIntegrationCore/pull/2 should fix that.
