### ISSUE TITLE
Make command feedback information toggleable

### ISSUE THREAD

**Issue by Drullkus** [MiraWaNeko/DiscordIntegration#149]
Hi there! I've got some commands set up for the bridge including the `!kill <>` which relays to the `/kill <>` command, but I'd like a way to be able to prevent the feedback from appearing in the channel.

<img width="411" alt="screen shot 2018-05-28 at 9 26 25 pm" src="https://user-images.githubusercontent.com/5010174/40638090-efb5c562-62bd-11e8-93af-9a59e493dfb0.png">

I'd like to keep command feedback from different commands though. Just `/kill @e[type=item]` gets super spammy and the bot gets throttled deeply by Discord itself.

**Comment by Mijago** [comment]
This should do the work.
I tested it with a new local instance, I registered a few commands with and without the new flag and it worked flawless.
After further testing I'll create a PR (or two, in this case).

@Chikachi can you have a look at the two commits whether the changes are OK for you?

**Comment by MiraWaNeko** [comment]
@Mijago LGTM
