### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by JohnnyWoong** [MiraWaNeko/DiscordIntegration#152]
### Base informations
**Minecraft version:*1.12.2*

**DiscordIntegration version:*3.0.5*

**Server type and version:** *Forge/Spigot/Sponge*
spongeforge
**Link to pastebin with (censored) config:** *Optional*
https://gist.github.com/JohnnyWongC/2ac58b2caf49fbbccb28e2b6bbd185c9

### Expected behavior
Just No Working
### Steps to reproduce
After i write the bot token and channel id ,and restart server,its does't work

**Comment by Mijago** [comment]
Do you have any log messages that tell anything about DiscordIntegration?
What *exactly* is not working?  Does the Bot connect to Discord (do you see it online)?

Please note that for MC->Discord you need to add them to the minecraft.dimensions.generic.discordChannel array.

~~For Discord->MC you need to set discord.channels.channels[your channel id].canExecuteCommands to true (ignore this, this value is currently ignored by the bot)~~

**Comment by JohnnyWoong** [comment]
Sry,Dont see the minecraft.dimensions.generic.discordChannel before.then what is discord.channels.channels do?

**Comment by JohnnyWoong** [comment]
Now is working.thx :)

**Comment by Mijago** [comment]
As it is working, I'm closing this issue.
