### ISSUE TITLE
How to show server info?

### ISSUE THREAD

**Issue by JohnnyWoong** [MiraWaNeko/DiscordIntegration#154]
How to show server info just like that

![qq 20180604224029](https://user-images.githubusercontent.com/5661094/40923838-69160342-6848-11e8-83ec-97e923e1a30c.png)

**Comment by Mijago** [comment]
Fun Fact: I am implementing this exactly at this moment.

So you can not do this *yet*, but you can do it soon.

**Comment by MiraWaNeko** [comment]
Duplicate of #134

**Comment by JohnnyWoong** [comment]
Nice to hear than,hope can use it in soon,thx :)
