### ISSUE TITLE
Webhook not working

### ISSUE THREAD

**Issue by jake-walker** [MiraWaNeko/DiscordIntegration#158]
### Base informations
**Minecraft version:**
1.7.10
**DiscordIntegration version:**
3.0.5
**Server type and version:** *Forge/Spigot/Sponge*
Forge
**Link to pastebin with (censored) config:** *Optional*
https://pastebin.com/8XuK7unM

### Expected behavior
I'd expect players chatting and executing commands to be shown in a webhook message with the user's Minecraft name as the name and the user's Minecraft avatar as the profile picture.
### Actual behavior
These messages come from the actual bot account:
![](https://u.jakew.me/selif/xtc9dap3.png)
### Steps to reproduce
Chat and execute in the server.

**Comment by Mijago** [comment]
Do normal chat messages work with the webhook?

**Comment by jake-walker** [comment]
No, the Webhook isn't working at all.

**Comment by Noranecore** [comment]
I have this issue too

**Comment by Mijago** [comment]
@PonyWithAnAK Also on 1.7.10?

**Comment by Noranecore** [comment]
@Mijago yeah I'm using it on my Project Ozone 2 server.
