### ISSUE TITLE
Cant use

### ISSUE THREAD

**Issue by JohnnyWoong** [MiraWaNeko/DiscordIntegration#160]
log show:
[chikachi.discord.repack.org.slf4j.helpers.Util:report:128]: SLF4J: cant load class "org.slf4j.impl.StaticLoggerBinder".

the bot still offline

**Comment by Mijago** [comment]
Normally you should be able to ignore this message.
Could you give more information about the error log and your configuration?
Minecraft Version, DI-Version, Configuration (w/o token) ....

**Comment by JohnnyWoong** [comment]
MC Version:1.12.2
DI Version . 3.0.5
actually it was work before,until  07.11 ,but i didt change anything 
```json
{
  "discord": {
    "token": "* * *",
    "ignoresBots": true,
    "allowLinking": true,
    "ignoresUsers": [],
    "channels": {
      "generic": {
        "commandPrefix": "!",
        "canExecuteCommands": false,
        "stripMinecraftCodes": true,
        "allowDMCommands": false,
        "relayChat": true,
        "messages": {
          "chatMessage": "[{USER}] {MESSAGE}"
        },
        "commands": []
      },
      "channels": {
         "* * *": {}
      }
    }
  },
  "minecraft": {
    "dimensions": {
      "generic": {
        "ignoreFakePlayerChat": true,
        "relaySayCommand": true,
        "relayMeCommand": true,
        "canMentionEveryone": false,
        "canMentionHere": false,
        "messageIgnoreRegex": [],
        "relayServerStart": true,
        "relayServerStop": true,
        "relayServerCrash": true,
        "chatPrefix": "",
        "canMentionUsers": true,
        "canMentionRoles": true,
        "discordChannel": [* * *],
        "relayAchievements": true,
        "relayChat": true,
        "relayCommands": true,
        "relayPlayerJoin": true,
        "relayPlayerLeave": true,
        "relayPlayerDeath": true,
        "messages": {
          "chatMessage": {
            "normal": "**[{USER}]** {MESSAGE}",
            "webhook": "{MESSAGE}"
          },
          "command": {
            "normal": "**[{USER}]** 执行了命令 **{COMMAND} {ARGUMENTS}**",
            "webhook": "*executed **{COMMAND} {ARGUMENTS}***"
          },
          "playerJoin": {
            "normal": "**{USER}** 加入了游戏!",
            "webhook": "*Joined the server!*"
          },
          "playerLeave": {
            "normal": "**{USER}** 离开了游戏!",
            "webhook": "*Left the server!*"
          },
          "playerDeath": {
            "normal": "**{USER}** 丢失了性命 {REASON}!",
            "webhook": "*{REASON}*"
          },
          "achievement": {
            "normal": "**{USER}** 达成了成就 **{ACHIEVEMENT}**!\n*{DESCRIPTION}*",
            "webhook": "*Gained the achievement **{ACHIEVEMENT}**!\n{DESCRIPTION}*"
          },
          "serverStart": "服务器开启!",
          "serverStop": "服务器停止!",
          "serverCrash": "监测到服务器崩溃!"
        }
      },
      "dimensions": {}
    },
    "integrations": {
      "dynmapEnabled": true
    }
  },
  "imc": {
    "enabled": true,
    "mode": "whitelist",
    "list": []
  }
}		
```

**Comment by JohnnyWoong** [comment]
19.07 10:27:53 [服务器] 服务器线程/信息 [STDERR]: [chikachi.discord.repack.org.slf4j.helpers.Util:report:128]: SLF4J: 无法成功加载 class "org.slf4j.impl.StaticLoggerBinder".
19.07 10:27:53 [服务器] 服务器线程/信息 [STDERR]: [chikachi.discord.repack.org.slf4j.helpers.Util:report:128]: SLF4J: Defaulting to no-operation (NOP) logger implementation
19.07 10:27:54 [服务器] JDA RateLimit-Queue Pool - Thread 1/信息 [STDERR]: [chikachi.discord.repack.org.slf4j.helpers.Util:report:128]: SLF4J: 无法成功加载 class "org.slf4j.impl.StaticMDCBinder".
19.07 10:28:03 [服务器] Thread-10/错误 [excompressum]: Could not load remote skins for auto sieve: 
19.07 10:28:21 [服务器] JDA RateLimit-Queue Pool - Thread 1/信息 [STDERR]: [chikachi.discord.repack.net.dv8tion.jda.core.utils.SimpleLogger:write:277]: [JDA RateLimit-Queue Pool - Thread 1] 错误 Requester - Requester timed out while executing a request
19.07 10:28:21 [服务器] JDA RateLimit-Queue Pool - Thread 1/信息 [STDERR]: [chikachi.discord.repack.net.dv8tion.jda.core.utils.SimpleLogger:log:272]: 	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:124)
19.07 10:28:21 [服务器] JDA RateLimit-Queue Pool - Thread 1/信息 [STDERR]: [chikachi.discord.repack.net.dv8tion.jda.core.utils.SimpleLogger:log:272]: 	at okhttp3.internal.connection.Real连接ion.connectSocket(Real连接ion.java:223)

**Comment by KenwoodFox** [comment]
Never solved? I have this issue.
