### ISSUE TITLE
Unable to achieve

### ISSUE THREAD

**Issue by utoc** [MiraWaNeko/DiscordIntegration#17]
Title is not a personal reflection ;)

Using:

DiscordIntegration-mc1.10.2-2.0.0
Forge-1.10.2-12.18.1.2045-installer
on Minecraft 1.10.2

I started a completely new world on the server; tested with commands like !tps with no issues, however, upon opening my inventory and waiting with baited breath for my congratulatory achievement from Minecraft, I got an error on the console, showing here: http://pastebin.com/DNJKeJgU

I got one iteration of the error for each time I opened my inventory.

Reverting to the previous version of ChikachiDiscord mc1.10.2-1.4.0 cleared the error and reinstated my ability to achieve.

**Comment by MiraWaNeko** [comment]
Sorry about that, it seems I missed the renaming of the mod at one tiny, but important, spot.

2.0.1 is now out - https://minecraft.curseforge.com/projects/discordintegration/files/2320828

**Comment by utoc** [comment]
Tested, working as intended
