### ISSUE TITLE
Other Discord bot messages are ignored

### ISSUE THREAD

**Issue by Fenrirthviti** [MiraWaNeko/DiscordIntegration#173]
### Base informations
**Minecraft version:** 1.12.2

**DiscordIntegration version:** 3.0.5

**Server type and version:** *Forge-1.12.2-14.23.5.2784*

**Link to pastebin with (censored) config:** *Default*

### Expected behavior

I have an IRC integration set up with my Discord server, and when messages are sent from IRC <-> Discord, the messages from the IRC bot should then relayed in-game to Minecraft.

### Actual behavior

All messages from the IRC -> Discord via the bot are ignored and not sent to Minecraft. Tested with other bots as well. Messages from MC -> Discord are picked up by the IRC bot and properly relayed.

### Steps to reproduce

Add another bot to your Discord server
Have it send any message to the channel the Discordintegration bot is monitoring
Observe that message is not sent to Minecraft

**Comment by Ricket** [comment]
For the sake of easiest reproducing, can you say which discord IRC bot you're using? Maybe this is an issue with all discord bots or maybe it's specific to that particular one.

**Comment by Ricket** [comment]
Hey look, there's a config option for that:

```
    "ignoresBots": true, // Should DiscordIntegration ignore Discord bots
```

Change that true to a false in your config, and you should be good.

**Comment by Fenrirthviti** [comment]
Missed that cause it's at the top of the config instead of where most of the other chat options are. Thanks!
