### ISSUE TITLE
Outdated wiki

### ISSUE THREAD

**Issue by Czechball** [MiraWaNeko/DiscordIntegration#176]
The config explanation (https://github.com/Chikachi/DiscordIntegration/wiki/Config-Explanation) is outdated, it doesn't match the newest config file... And I truly have no idea how to edit it properly.

**Comment by MiraWaNeko** [comment]
Have you tried using `Config Explanation v3`?
https://github.com/Chikachi/DiscordIntegration/wiki/Config-Explanation-v3

**Comment by Czechball** [comment]
Yes, that worked. Thanks. The links are kinda misleading....
