### ISSUE TITLE
Discord -> Minecraft is working fine, but Minecraft - > Discord isn't working.

### ISSUE THREAD

**Issue by Orepheus** [MiraWaNeko/DiscordIntegration#177]
### Base informations
**Minecraft version:** 1.12.2

**DiscordIntegration version:** 3.0.5

**Server type and version:** SpongeForge 1.12.2-2705-8.0.0-BETA-3462

### Expected behavior
Discord messages are sent to Minecraft chat, and Minecraft chat is sent to discord, per usual.

### Actual behavior
When people type in #server_chat, the messages are relayed to the Minecraft server like they usually would. However, when someone says anything or does any commands in the Minecraft server, nothing whatsoever is relayed back to Discord.

### Steps to reproduce
N/A

**Comment by ZensiertGamer** [comment]
Have the same Problem
But i am using "normal" Forge 14.23.5.2815

**Comment by ghost** [comment]
same here cannot get this to work. It refuses to write in the chat.
Except for reactions to custom commands etc.

**Comment by jusvit** [comment]
@Orepheus @ZensiertGamer  @TellyO3 

![Capture](https://user-images.githubusercontent.com/4002351/57408392-e9e70300-7228-11e9-9e6a-957a79eba246.PNG)

**Comment by IdolonInMachina** [comment]
I'm also having this issue. Discord to Minecraft works fine, however Minecraft to Discord does not work. My config is set out as shown in your example @Dimmerworld

**Comment by Ricket** [comment]
First of all, as folks get this problem figured out, please post what fixed it for you.

I would suggest next to double check that your bot's role has the Send Messages permission. And that it can post to the particular channel.

For advanced users, you could try making the bot send a message to the channel using the API, and see if you get an error back.

Also is anyone seeing errors in the server log? I would expect each message that fails to send to discord would have an error message in the server log, but maybe it's not the case.

**Comment by IdolonInMachina** [comment]
My bot definitely has the send messages permission, as it can respond to commands in the channel such as tps and online

**Comment by IdolonInMachina** [comment]
I checked the debug log as well, I don't see any error messages.

**Comment by LukaTheHero** [comment]
I have the exact same problem with normal forge

**Comment by IdolonInMachina** [comment]
Yeah its still an issue for me
