### ISSUE TITLE
coding issues

### ISSUE THREAD

**Issue by JoshuaStutzman** [MiraWaNeko/DiscordIntegration#178]
### Base informations
**Minecraft version:**
1.7.10
**DiscordIntegration version:**
3.0.5
**Server type and version:** *Forge/Spigot/Sponge*1
1.7.10-Forge10.13.4.1614-1.7.10
**Link to pastebin with (censored) config:** *Optional*

### Expected behavior
copy and paste the channel link.
### Actual behavior
i can copy it in but then it says it is a bad string on line two of the code i'll paste below.
### Steps to reproduce
"channels": {
         {"571012643515662342": }
      }   
  },

**Comment by Mijago** [comment]
Your example is not valid JSON.
Try something line this:
`
    "channels": {
        "571012643515662342":  {
        }
    },
`

**Comment by JoshuaStutzman** [comment]
I think i got it now. i had the {} on the wrong side, i solved that right before you responded. Thanks.
I have fixed this but the bot does not even come online in discord when i start the server or chat is minecraft. Do you have a fix for this?

**Comment by jusvit** [comment]
> I think i got it now. i had the {} on the wrong side, i solved that right before you responded. Thanks.
> I have fixed this but the bot does not even come online in discord when i start the server or chat is minecraft. Do you have a fix for this?

Have you ensured your token is correct?
https://github.com/Chikachi/DiscordIntegration/wiki/How-to-get-a-token-and-channel-ID-for-Discord
