### ISSUE TITLE
Emoji to plaintext

### ISSUE THREAD

**Issue by ghost** [MiraWaNeko/DiscordIntegration#18]
https://github.com/Chikachi/DiscordIntegration/issues/11

It seems only in-game text (eg. `:D`) is being converted to Discord emojis (`:smile:`), but not the other way around.

**Comment by MiraWaNeko** [comment]
They are actually getting converted Discord => Minecraft.
Discord is sending the emojis as the UTF-8 character, so I decided to convert to the smiley to their text alias, but yes, I should add a conversion of the more common used ones as your example is part of.

**Comment by MiraWaNeko** [comment]
Should be fixed in 2.1.0
