### ISSUE TITLE
Coloured message format

### ISSUE THREAD

**Issue by ghost** [MiraWaNeko/DiscordIntegration#19]
Ability to customise the in-game message format with colours would be nice.

eg. `&5[Discord] &f%USER%&7: %MESSAGE%`

**Comment by MiraWaNeko** [comment]
The way I'm splitting the message up doesn't support this so I'm adding a way to switch over to allow in-game message format

**Comment by MiraWaNeko** [comment]
Should be fixed in 2.1.0
