### ISSUE TITLE
No ID?

### ISSUE THREAD

**Issue by TehFoxFire** [MiraWaNeko/DiscordIntegration#20]
In the tutorial you say that I need to Rclick on the channel that I want and then click Copy ID. The problem is that the button doesn't exist! Now Im wondering if that was removed in a update to discord or something but now my question is now how do I get the ID? If you could help me I would very much appreciate it.

**Comment by MiraWaNeko** [comment]
Did you enable developer mode?

**Comment by TehFoxFire** [comment]
Nope that was my problem, thanks that fixed it!
