### ISSUE TITLE
Can I make messages from discord be prefixed with [Discord]?

### ISSUE THREAD

**Issue by vizthex123** [MiraWaNeko/DiscordIntegration#209]
Title. I can't find anything about it on the wiki and don't want to risk breaking things by trying it on my own.

**Comment by SizableShrimp** [comment]
Yes, this is possible. I admit the wiki isn't up to where it should be right now so it may be hard to find this option. It is named `chatMessage` under channel options. See below for an example config that I personally use.

```
    "channels": {
      "generic": {
        "commandPrefix": "!",
        "canExecuteCommands": false,
        "stripMinecraftCodes": true,
        "allowDMCommands": true,
        "relayChat": true,
        "messages": {
          "chatMessage": "&9[Discord] &r&9{USER} &r&8» &r&9{MESSAGE}"
         }
       }
     }
```

**Comment by vizthex123** [comment]
Thanks, glad I got a quick response.
