### ISSUE TITLE
Custom commands permission denied

### ISSUE THREAD

**Issue by ThePoet444** [MiraWaNeko/DiscordIntegration#21]
I'm on 1.7.10 still, This was happening on version 1.4 and 2.01. I added roles to the TPS command, and it works fine. I add a custom command copied right from the wiki and it tells me I do not have permission to use this command. I'm the admin of the discord and minecraft servers. The built in commands work just fine and behave as normal. Anything custom though and it doesn't work. 

[Pastebin config](http://pastebin.com/MZTc51Yk)

I have reloaded and even restarted the minecraft server to no change.

**Comment by MiraWaNeko** [comment]
Do you have a role called "Admin" and is your discord user assigned to that role?

Just tested here and it works fine.

**Comment by ThePoet444** [comment]
Yes, and I'm the discord server owner. If I add "Admin" to the tps command it works fine, if I add "Admin" to a custom command, it tells me I don't have permission. Same for a custom command where there are no roles assigned.

**Comment by ThePoet444** [comment]
Apologies I should have done this sooner. This is a modlist of the server I'm running [Pastebin modlist](http://pastebin.com/gnVr8nAR).  Also using the 1614 version of Forge.

**Comment by MiraWaNeko** [comment]
I just recreated the modpack here and it works fine. Can't reproduce the issue.

**Comment by ThePoet444** [comment]
ok.. this is just weird then. I guess I can live without custom commands..  cause that's the only thing not working..  I'll try and redownload/install see if that helps. Thanks for checking!

**Comment by MiraWaNeko** [comment]
BTW the responses you get is the Minecraft server's response and not the mod responding.

The mod is using it's own CommandSender which should have access to all commands as you can see at https://github.com/Chikachi/DiscordIntegration/blob/1.7.10/src/main/java/chikachi/discord/command/DiscordCommandSender.java#L52-L54

But there may be some config or another mod that changes how the commands check for permissions.

**Comment by ThePoet444** [comment]
I'm going to guess it's forgeessentials then. I'll have to go through their permissions list and see if I can figure it out. Thanks again!

**Comment by MapleSight** [comment]
Having the same issue here.

I agree the issue is Forge Essentials permissions. In order for DI to be able to use a command they need perms for it. I enabled the fake player option in the config, but cant seem to find the fakeplayer. @Chikachi Can you give me a hand on
