### ISSUE TITLE
Relay bots broken after discord API 

### ISSUE THREAD

**Issue by Gunner76th** [MiraWaNeko/DiscordIntegration#216]
### Base informations
**Minecraft version:**
All
**DiscordIntegration version:**
All
**Server type and version:** *Forge/Spigot/Sponge*
N/A
**Link to pastebin with (censored) config:** *Optional*

Due to a recent update to the Discord API system that happened during the night between October 26 and October 27, any Minecraft server that is running the relay bot and is restarted will lose the ability to use their bot.  The screen shot shows the error that it's currently appearing on the server console if you restart your server.  
This will affect ALL minecraft versions,  all forge,  sponge,  and spigot versions,  and all current versions of Discord Integrations.  

![Screenshot_20201027-174943_Chrome](https://user-images.githubusercontent.com/5566872/97365965-e744f700-187c-11eb-9f0f-b1affc6541fe.jpg)

![Screenshot_20201027-174952_Chrome](https://user-images.githubusercontent.com/5566872/97365981-ef9d3200-187c-11eb-8ac4-53176a7580de.jpg)

![Screenshot_20201027-175003_Chrome](https://user-images.githubusercontent.com/5566872/97366002-f7f56d00-187c-11eb-8c11-537b1e2a7959.jpg)

![Screenshot_20201027-175011_Chrome](https://user-images.githubusercontent.com/5566872/97366014-fd52b780-187c-11eb-980a-1c54a6dd19a6.jpg)

**Comment by chunkedelement** [comment]
Hey go into discord dev application and settings the bot and enable "SERVER MEMBERS INTENT" in order to fix, both of our server bots quit. Also see and thanks to: https://github.com/ErdbeerbaerLP/Discord-Chat-Integration/issues/128#issuecomment-717553307
![Screenshot 2020-10-27 223819](https://user-images.githubusercontent.com/34798853/97383987-28e99800-18a5-11eb-984d-c5eb1dfbf064.png)

**Comment by chunkedelement** [comment]
That seemed to have fixed the issue both bots now communicating again.

**Comment by Gunner76th** [comment]
Yeah I did that already and then rebooted my server before posting those screenshots.  It's why I reported it.

**Comment by Gunner76th** [comment]
Ok so just double checked things and somehow I have 2 discord bots/apps with the same name.  I just flipped the switches on the other one to set if that fixed things.

**Comment by Gunner76th** [comment]
Ok so yeah,  it was a PEBKAC issue.  Once I did the above it started working.  Now to remove / rename the other app.
