### ISSUE TITLE
No messages appear in Discord

### ISSUE THREAD

**Issue by Symsyr** [MiraWaNeko/DiscordIntegration#217]
### Base informations
**Minecraft version:**
1.12.2
**DiscordIntegration version:**
3.0.5
**Server type and version:** *Forge/Spigot/Sponge*
Forge 2854
**Link to pastebin with (censored) config:** *Optional*

### Expected behavior
Server start and stop messages transferring to Discord channel
### Actual behavior
Nothing happens now
### Steps to reproduce
This was working fine on 26OCT20 and then just stopped transferring messages to Discord. I have another server on 1.15.2 with a separate Integration mod installed that is doing the same thing, stopped at the same time. I'm guessing Discord changed something to break it

**Comment by MiraWaNeko** [comment]
Try what was suggested in this comment https://github.com/Chikachi/DiscordIntegration/issues/216#issuecomment-717658151

**Comment by Symsyr** [comment]
That fixed it, thank you
