### ISSUE TITLE
All commands returning "Unknown Command"

### ISSUE THREAD

**Issue by imranh101** [MiraWaNeko/DiscordIntegration#22]
Hello, having an issue here. Have custom command

{"name":"whitelist","cmd":"whitelist %args%","roles":"Admin"}

Whenever I do !whitelist namehere in Discord, bot in discord returns unknown command, try /help for a list of commands

Have also tried 

{"name":"whitelist","cmd":"/whitelist %args%","roles":"Admin"}

Also returns same output.

Have also tried other commands like /op and /kick, all are returning same output.

Chat pass-through is working fine  as are death messages, etc.

**Comment by MiraWaNeko** [comment]
Which Minecraft version and which mod version?

**Comment by MiraWaNeko** [comment]
This setup is working for me.
![image](https://cloud.githubusercontent.com/assets/10409177/17837617/f08f46d2-67b7-11e6-82fd-3a26d523ec0e.png)

**Comment by imranh101** [comment]
Using Minecrafat 1.7.10 and discordintegration 1.7.10-2.0.1 ... strange

**Comment by imranh101** [comment]
Have I messed something up here? Apologies for messyness for some reason I
can't get any program to open it up with proper formatting.

{"discord":{"token":"mytokenishere","channel":"mychannelishere","ignoreBots":false,"commands":{"prefix":"!","online":{"enabled":true,"roles":[],"aliases":[]},"tps":{"enabled":false,"roles":[],"aliases":[],"colored":false},"unstuck":{"enabled":false,"roles":["AdminRoleHere"],"aliases":[]},"custom":[{"name":"op","cmd":"op
%args%","roles":"Admin"},{"name":"whitelist","cmd":"whitelist
%args%","roles":"Admin"}]}},"messages":{"discord":{"chat":{"enabled":true,"message":"<**%USER%**>
%MESSAGE%","relaySayCommand":true,"useEmotes":true},"death":{"enabled":true,"message":"**%USER%**
%MESSAGE%"},"achievement":{"enabled":true,"message":"Congrats to **%USER%**
for earning the achievement **%ACHIEVEMENT%**
(%DESCRIPTION%)"},"join":{"enabled":true,"message":"**%USER%** has joined
the server!"},"leave":{"enabled":true,"message":"**%USER%** left the
server!"},"startup":{"enabled":false,"message":"**Server
started**"},"shutdown":{"enabled":false,"message":"**Server
shutdown**"}},"minecraft":{"chat":{"enabled":true,"message":"<**%USER%**>
%MESSAGE%","maxLength":-1,"usernameColor":"red"}}},"experimental":{"fakePlayers":false}}

**Comment by imranh101** [comment]
Also note these commands do work fine when simply typed in to server
console manually

**Comment by MiraWaNeko** [comment]
Have you tried running the server without any other mods and see if the issue still occurs?

If you try it on your current server, remember to backup the world ;)
