### ISSUE TITLE
Minecraft users are unable to click on links coming from Discord users

### ISSUE THREAD

**Issue by utoc** [MiraWaNeko/DiscordIntegration#23]
Channel Perms: http://i.imgur.com/0ISu3Ru.png
Discord config file: http://pastebin.com/nEhcsULe
In-game screenshot: http://imgur.com/nU7nMyY

I am not sure if this is intended behavior or not but we're unable to click links from Discord users' on the MC side.  We can post links in MC and click them in Discord all day long.  Its really odd behavior.  You can see in the screenshot that the links are underlined and all like a hyperlink but clicking them does nothing.

Thoughts?

Running FML 2073, DiscordIntegration 2.0.1

**Comment by MiraWaNeko** [comment]
Should be fixed in 2.1.0

**Comment by utoc** [comment]
Just tested, still a no-go.  Just curious, on the servers you frequent, are you unable to reproduce this on your end?

**Comment by MiraWaNeko** [comment]
I haven't played Minecraft in months now as I don't have much time for it atm.

Did you enable `customFormatting` as told in the [CHANGELOG](https://github.com/Chikachi/DiscordIntegration/blob/1.10.2/CHANGELOG.md#210)?  
The reason is that the way I made the creation of the chat message breaks the link handlers and `customFormatting` is handling them differently and doesn't break it.

**Comment by utoc** [comment]
Log output: `
[12:30:56] [Client thread/INFO]: [CHAT] <utoc> §9§nhttps://minecraft.curseforge.com/projects/reborncore/files/2323518§r
`

Relevant config:
`"messages": {
        "discord": {
            "chat": {
                "customFormatting": true,
                "enabled": true,
                "message": "<%USER%> %MESSAGE%",
                "relaySayCommand": true
            },
`

Thank you for taking the time to assist me with the little things in life.

**EDIT** I AM AN IDIOT THAT DOES NOT FULLY READ INSTRUCTIONS

Thank you, I have it working by putting customFormatting in the right place :)

**Comment by MiraWaNeko** [comment]
Glad you got it to work :)
