### ISSUE TITLE
CustomFormatting using & gives weird character

### ISSUE THREAD

**Issue by MiraWaNeko** [MiraWaNeko/DiscordIntegration#26]
Temp solution is to use the proper § character instead of &

Using &
![2016-09-15_22-23-00_e5765e9e-f17c-4c28-986c-8e762da65ece](https://cloud.githubusercontent.com/assets/10409177/18577590/ee020bb0-7bea-11e6-81e4-5a8eeb191929.png)

Using §
![2016-09-15_23-07-12_ddb2ac5a-6c4b-412e-b448-024892dbe239](https://cloud.githubusercontent.com/assets/10409177/18577606/0d0010ca-7beb-11e6-9872-5fbd7dcaef59.png)

**Comment by lilmoefow** [comment]
When i use the "proper § character instead of &"  my chat just looks like this
http://imgur.com/a/qd7Lv

here is what i have the config set to

```
"minecraft": {
  "chat": {
    "enabled": true,
    "message": "[§bDiscord§f]:%USER% §7%MESSAGE%",
    "maxLength": -1,
    "usernameColor": "white",
    "customFormatting": true
  }
}
```

  },

**Comment by MiraWaNeko** [comment]
Could you check which encoding the config file is saved with?
(ISO 8859-1, windows-1252, utf-8, etc)

**Comment by lilmoefow** [comment]
Im not 100% sure what you mean by that, but here is a copy of the config im using (with the bot token and channel id removed)

http://pastebin.com/jSFYwvKE

The Config gets saved as a .json file?? if that is what you mean.

**Comment by ReaperAngels** [comment]
Instead of "§", use &. So in your case it will be "&b"
