### ISSUE TITLE
Crash Issue when bot has no permission to chat in a discord channel.

### ISSUE THREAD

**Issue by StoneLegion** [MiraWaNeko/DiscordIntegration#32]
I derped up and forgot to give the bot permissions when changing permissions on my channel. And it caused this really nasty crash:

http://pastebin.com/gyyLkYVA

It's a user derp but of course crashing should not happen :)

**Comment by MiraWaNeko** [comment]
Thanks for reporting this, it'll be fixed ASAP :)

**Comment by StevenB83** [comment]
What's the status on this? It's user error yes :p but crash is not fun, could easily change permission on a channel and then server crashes.

**Comment by MiraWaNeko** [comment]
I'm currently rewriting the whole mod, where this won't be an issue

**Comment by Gunner76th** [comment]
Do we have an update as to when this issue will be resolved and a fix pushed out to Curse?
