### ISSUE TITLE
Server to Channel Messages Contain Color Codes

### ISSUE THREAD

**Issue by MapleSight** [MiraWaNeko/DiscordIntegration#33]
Wonderful mod and it works great.

Just a couple characters and changes that I think need to be implemented or changed. When a player joins my server the discord app says "§9 USER §r has joined the server!" in the channel because I gave their names colors. Is there a way to scrub the color codes away from messages sent to the discord server?

Thank you for your time.

**Comment by MrIngelborn** [comment]
Haveing the same issue. No problem when saying somethind though.
![capture](https://cloud.githubusercontent.com/assets/4086714/21334795/52e245f4-c65a-11e6-8150-8da72ec24140.PNG)
EDIT: Using version: DiscordIntegration-mc1.10.2-2.1.0.jar
