### ISSUE TITLE
Version 2.1.0 does not load in MC 1.10.2

### ISSUE THREAD

**Issue by Routhinator** [MiraWaNeko/DiscordIntegration#35]
I'm trying to get this mod to work but it seems to do nothing when added to a 1.10.2 forge server. There are no errors, but also no configs or commands.

Trying 2.0.1 now.

### Update:

2.0.1 doesn't seem to load either.. no idea what's wrong. zip is in the Mod folder.

**Comment by MiraWaNeko** [comment]
Which Forge version?

**Comment by Routhinator** [comment]
Recommended: 

1.10.2 - 12.18.2.2099

**Comment by MiraWaNeko** [comment]
I just tested and it's working fine.

You wrote `zip is in the Mod folder` - it should be a .jar file in the `mods` folder
