### ISSUE TITLE
Request Multi-Channel Support.

### ISSUE THREAD

**Issue by axieum** [MiraWaNeko/DiscordIntegration#37]
I'm not sure if I'm jumping ahead of you, but if you haven't already considered Multi-Channel Support, please add it to your to-do list. 

Essentially, I'd like to setup another channel for Admin to execute "custom commands" (whitelist, tps, etc.). By having a separate channel, this is stop polluting our main Discord channel.

You could have the config support different settings for each channel, that is each channel is separate from each other but maintains the same options (cmds, enabled, chat format, etc.).

**Comment by Raawkun** [comment]
Or like being able to filter different types of messages to different channels - like achievements from ingame into #achievements or join/leave messages to a #joinleave channel etc. ;)

**Comment by MiraWaNeko** [comment]
This will be part of DiscordIntegration v3

**Comment by a-frenzy** [comment]
I'd like to be able to just add a second channel to the config
