### ISSUE TITLE
Multi Server Support

### ISSUE THREAD

**Issue by KitKat31337** [MiraWaNeko/DiscordIntegration#40]
I am using this on a pair of servers using a single Discord channel.  It would be nice if there were a way other than changing the prefix to have this handled.

**Comment by MiraWaNeko** [comment]
I only see a few ways to handle this

- Using prefix (as you said)
- Use a bot per server (this way you can also have the messages sent to the other servers for full conversation abilities)
- Use webhook in v3 (as this will show each user)

**Comment by MiraWaNeko** [comment]
All of these doesn't require me to change the code, if you have a better idea, just comment on this but for now I'm gonna close this.
