### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Sitherious** [MiraWaNeko/DiscordIntegration#42]
ReadingThread/INFO - STDOUT 01/16/2017 19:33:01
19:33:01[minetweaker.mc1102.server.MCServer:getPlayer:45]: Unsupported command sender: chikachi.discord.command.DiscordCommandSender@24b201f8 defaulting to server player!
[minetweaker.mc1102.server.MCServer:getPlayer:46]: player name: @sitherious
[minetweaker.mc1102.server.MCServer:getPlayer:47]: Please report to mod author if this is incorrect!
[minetweaker.mc1102.server.MCServer:getPlayer:45]: Unsupported command sender: chikachi.discord.command.DiscordCommandSender@24b201f8 defaulting to server player!
[minetweaker.mc1102.server.MCServer:getPlayer:46]: player name: @sitherious
[minetweaker.mc1102.server.MCServer:getPlayer:47]: Please report to mod author if this is incorrect!

**Comment by MiraWaNeko** [comment]
This seems like an issue in MineTweaker.

This happens as DiscordIntegration is using it's own command sender to be able to get responses for the different commands being executed by the mod and send the response back to Discord.
