### ISSUE TITLE
uChat compatibility

### ISSUE THREAD

**Issue by kaal-1** [MiraWaNeko/DiscordIntegration#45]
Do you think it's possible to add a feature so that only global channels in uChat (https://forums.spongepowered.org/t/thought-balloon-ultimatechat-v-1-7-0-api-5-6/17438) are sent to Discord?

Atm all chats (including staff and local) are being sent.

**Comment by MiraWaNeko** [comment]
As far as I can see, there's no good way for a Forge mod to listen to the events from a Sponge plugin.
I think the best way of achieving this would be to have uChat to communicate with DiscordIntegration with the messages that should be sent through.

**Comment by FabioZumbi12** [comment]
I think this is only possible as plugin and not as mod. Maybe you can suggest on sponge forums, or a version of this mio as sponge plugin. Btw now all channel commands and messages are listening to chat event like issue https://github.com/FabioZumbi12/UltimateChat/issues/21
