### ISSUE TITLE
UltimateChat Compatibility

### ISSUE THREAD

**Issue by Zuruckt** [MiraWaNeko/DiscordIntegration#52]
You use can colors if you use the colors codes in discord, i don't want that because that should be a privilege to VIPS, and only get the mensages that has been sent in /g, even tell is sent if you lock with someone and don't use /tell to send the mensages.
Here is the chat plugin link https://github.com/FabioZumbi12/UltimateChat

**Comment by MiraWaNeko** [comment]
This is something UltimateChat would have to do
See #45
