### ISSUE TITLE
Chat is showing messages for cancelled events

### ISSUE THREAD

**Issue by Alex-hawks** [MiraWaNeko/DiscordIntegration#53]
Sample: http://puu.sh/vpuqs/44c2107dd8.png
Another case is the Chat Detector from Random Things cancelling the chat event, but it is still sent to Discord. 
A solution is to lower the event priority of the events [here](https://github.com/Chikachi/DiscordIntegration/blob/1.10.2/src/main/java/chikachi/discord/listener/MinecraftListener.java) to EventPriority.LOWEST, and then check if the event was cancelled

**Comment by MiraWaNeko** [comment]
This will be fixed in v3
