### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by cauliflower69** [MiraWaNeko/DiscordIntegration#54]
Crash report - https://pastebin.com/u6jpTjJM

Using version 0.4.1 of this pack https://minecraft.curseforge.com/projects/age-of-engineering/files

It was working fine with earlier versions. Once we removed your mod the server booted.

**Comment by Ricket** [comment]
It looks like maybe the bot didn't have a needed permission to be able to send a message to the given channel. Did you remember to authorize the bot to your server & channel, per the wiki? You say it was working fine earlier though. Maybe someone removed the bot from your discord server? Or you typo'd the channel ID in the config file?

I would suggest to delete your config file and recreate it.
