### ISSUE TITLE
Having issue with the Custom Commands on 2.1.0 for 1.7.10

### ISSUE THREAD

**Issue by LeDemmers** [MiraWaNeko/DiscordIntegration#55]
Hello, Were having a small issue with the custom commands section. We believe we have it setup completely, and have looked over the JSON multiple times. We also tried giving the BOT full perms on the Discord to see if that changed how it worked.

We use the Semicolon for the prefix.
`;stuck DEMMERS`
Is a custom command. It looks like the following:
`{  "name": "stuck", "cmd": "/tp %1% ~ ~3 ~", "roles": [ "Admin" ] }`
The expected results in-game is that the user wherever they are standing is teleported up 3 blocks.
We've also tried using a different tag.
`{  "name": "stuck", "cmd": "/tp %args% ~ ~3 ~", "roles": [ "Admin" ] }`
Now, we run the command in the Discord, no error in the console. The command instead returns with, "You do not have permission to run this command"

**Comment by kaal-1** [comment]
I'm having a similar issue in 1.10, tps command works fine, but when I try to use any of the custom commands that have %args%, the bot says "You do not have permission to use this command!". Commands like /stop, /kickall (with no args) work just fine.

**Comment by MiraWaNeko** [comment]
DiscordIntegration is using a CommandSender that have permission to every command, the command that you're trying to execute must not be checking the permissions correctly and is therefore making Minecraft return "You do not have permission to run this command".

The "You do not have permission to run this command" message isn't DiscordIntegration's doing, but rather just what DiscordIntegration is getting back when trying to execute the command.
