### ISSUE TITLE
Custom commands with arguments not working

### ISSUE THREAD

**Issue by kaal-1** [MiraWaNeko/DiscordIntegration#56]
I have multiple custom commands, some with args and some without. Whenever I try to use a command with args, lets say !kick player reason or !tp player player2, the bot says "You do not have permission to use this command!". No error is shown in the console.

This doesn't happen when I use for example !killall (set to run /cofh killall), or !restart (set to run /stop).

Any suggestions on something I could try?

**Comment by MiraWaNeko** [comment]
DiscordIntegration is using a CommandSender that have permission to every command, the command that you're trying to execute must not be checking the permissions correctly and is therefore making Minecraft return "You do not have permission to run this command".

The "You do not have permission to run this command" message isn't DiscordIntegration's doing, but rather just what DiscordIntegration is getting back when trying to execute the command.
