### ISSUE TITLE
help channel wont work bot is connected

### ISSUE THREAD

**Issue by camatthew** [MiraWaNeko/DiscordIntegration#61]
here is my log 
https://hastebin.com/hiresasica.vbs

**Comment by MiraWaNeko** [comment]
`Cannot preform action due to a lack of Permission. Missing permission: MESSAGE_WRITE`
The bot doesn't have write permission

**Comment by camatthew** [comment]
yes it does

**Comment by camatthew** [comment]
I remember enabling write permission

**Comment by MiraWaNeko** [comment]
Try adding the permission directly on the channel you want it to be able to write in
