### ISSUE TITLE
[Bug] 1.10.2 Weird interaction reported to Crafttweaker tracker

### ISSUE THREAD

**Issue by MysticAura** [MiraWaNeko/DiscordIntegration#62]
[CT Issue here](https://github.com/jaredlll08/CraftTweaker/issues/245)

Thought you may want to take a peek. @Chikachi

**Comment by kaal-1** [comment]
In the v3 alpha version, the message is different. Command is not executed still..
[JDA MainWS-ReadThred/WARN] [Sponge]: No entity type is registered for class chikachi.discord.command.DiscordCommandSender

**Comment by MiraWaNeko** [comment]
This is expected behaviour from SpongeForge

> While it's normally a sign that a mod is doing something wrong, the two classes mentioned above appear to be various 'fake player' classes. Since these never actually get spawned into the world, you can safely ignore them.
> https://github.com/SpongePowered/SpongeForge/issues/1272#issuecomment-280957321
