### ISSUE TITLE
Unable to connect to channel

### ISSUE THREAD

**Issue by oitsjustjose** [MiraWaNeko/DiscordIntegration#63]
### Base informations
**Minecraft version:** 1.12

**DiscordIntegration version:** 3.0.0

**[Link to pastebin with (censored) config](https://pastebin.com/FGNMBwya)**

So, to be completely honest I'm not sure if I do not understand the config correctly, or if it's truly a bug. I can get *logged in* to my "bot" account fine, but I have fiddled with configs for 45 minutes and cannot get it to connect to my Discord channel! Is there something I'm doing completely wrong with this config file, or is it a bug? Let me know if you need more details!

**Comment by MiraWaNeko** [comment]
I can see you replaced "generic" with your channel ID - this isn't the right way to do it.
You need to add the channel ID to the "channels" object below it.

I have a wiki page for it, though a bit outdated.
https://github.com/Chikachi/DiscordIntegration/wiki/Config-Explanation-v3

I anticipated that people would have issues with the config, but this was the best way I could add all the flexibility into it.
I'm also working on a config generator site, where people just have to insert the informations and it'll create the config for you. It's still in it's early phases with a lot of config settings missing, but it might help you with the channel setup part.
https://wip.discordintegration.net/config/generator

**Comment by NielsPilgaard** [comment]
I'm having issues with the config aswell, do you have time to find the mistake I've made? :)
I hope it's alright I didn't make a seperate issue, I don't wanna clutter up your git with questions.

[Config](https://pastebin.com/SNgUximX)

**Comment by MiraWaNeko** [comment]
I just took the config from the original message and fixed it - https://pastebin.com/r6fMuCJq

**Comment by NielsPilgaard** [comment]
Thanks a lot, however it still doesn't work - The bot is visible in the channel now, it just doesn't do anything.

**Comment by oitsjustjose** [comment]
And my bot wasn't even connecting until I forced it, but it's not passing messages on either.. :/

**Comment by MiraWaNeko** [comment]
Please change `minecraft` > `dimensions` > `generic` > `discordChannel` to an array of Discord channel IDs that you want to relay to.

It's a bug it's becoming `true`.

Example:
```json
  "discordChannel": [ 123456789012345678, 123456789012345679 ]
```
