### ISSUE TITLE
Webhook Not Connecting

### ISSUE THREAD

**Issue by ChloeDawn** [MiraWaNeko/DiscordIntegration#64]
` Failed to connect to Discord: The provided token is invalid!`

When trying to reload the config using a webhook token.

**Minecraft version:** 1.12
**DiscordIntegration version:** [3.0.0](https://minecraft.curseforge.com/projects/discordintegration/files/2458271)

**Comment by MiraWaNeko** [comment]
The webhook url should be put in the settings for the specific channel and not in token

**Comment by ChloeDawn** [comment]
Ah, my bad. How do I define the webhook url? I don't see an example of an entry for it on the wiki page

**Comment by MiraWaNeko** [comment]
Added it to the wiki page now
