### ISSUE TITLE
Bot joining too soon [McMyAdmin]

### ISSUE THREAD

**Issue by thefinaldegree** [MiraWaNeko/DiscordIntegration#69]
### Base informations
**Minecraft version: 1.10.2**

**DiscordIntegration version: 3.0.0**

**Link to pastebin with (censored) config: [https://pastebin.com/hAmeUsjw](https://pastebin.com/hAmeUsjw)** *Optional*

### Expected behavior
Bot joining

### Actual behavior
Bot unable to join

### Steps to reproduce
Starting server. Error message: [https://pastebin.com/09Lq92dM](https://pastebin.com/09Lq92dM)

**Comment by thefinaldegree** [comment]
PS. I am aware you are on holiday - don't bother looking into this at all until after you get back! :smile:

**Comment by jc2xs** [comment]
You may want to take a look at some of the closed cases.  You are missing another entry where you need to put in the discord channel ID a second time.  Take a look here:  https://github.com/Chikachi/DiscordIntegration/issues/65

I was able to get mine to work with that additional info.

**Comment by thefinaldegree** [comment]
@jc2xs Thanks for the info.
I had to change minecraft > dimensions > generic > discordChannel (which was previously set to 'true'):
`        "discordChannel": [
          xxxxxxxxxxxxxxxxxxxxx
        ],`

**Comment by MiraWaNeko** [comment]
@thefinaldegree Did you solve this?
