### ISSUE TITLE
Messages not being disabled

### ISSUE THREAD

**Issue by cauliflower69** [MiraWaNeko/DiscordIntegration#7]
Is there anyway to disable the server messages. http://imgur.com/pBBrBQ6

**Comment by MiraWaNeko** [comment]
Not currently, but I'll add a config option for it

**Comment by cauliflower69** [comment]
Thanks, that makes it an ideal option

**Comment by MiraWaNeko** [comment]
Will be in the next release

**Comment by cauliflower69** [comment]
Thanks again.
