### ISSUE TITLE
Custom commands don't work with arguments

### ISSUE THREAD

**Issue by Netruk44** [MiraWaNeko/DiscordIntegration#71]
https://github.com/Chikachi/DiscordIntegration/blob/cc62086e1ac0e560656e21427de60652df6b7f3e/src/main/java/chikachi/discord/core/config/discord/CommandConfig.java#L53

Replace takes a string literal, not a regular expression. So unless the argument is preceeded by (?i), arguments won't work.

**Comment by MiraWaNeko** [comment]
Good catch!

**Comment by MiraWaNeko** [comment]
Fixed in 3.0.1
