### ISSUE TITLE
Discord to MC works but MC to Discord doesn't

### ISSUE THREAD

**Issue by cauliflower69** [MiraWaNeko/DiscordIntegration#72]
### Base informations
**Minecraft version:** 
1.12.0
**DiscordIntegration version:** 
DiscordIntegration-mc1.12-3.0.0.jar
**Link to pastebin with (censored) config:** *Optional*
https://pastebin.com/QCgBMdGA

### Expected behavior
To work like earlier versions
### Actual behavior
Server start / shutdown not displaying. Discord to MC works but MC to Discord does not
### Steps to reproduce
Use my config and it should reproduce the issue.

**Comment by grandrolf** [comment]
Change line 58 in the json
From:
"discordChannel": true,

To:
"discordChannel": [INPUT CHANNEL ID HERE],

And try again (restart server or use in-game command to reload the config)

**Comment by cauliflower69** [comment]
@grandrolf That fixed it thanks

**Comment by Aaronstar-McClure** [comment]
same problem, i cant figure it out
https://pastebin.com/7CVdrapK

**Comment by Aaronstar-McClure** [comment]
the channel is 348278072677629953
the server is 97719085462196224

**Comment by Tokeli** [comment]
You don't put the server in the "discordChannel" line, you put the channel ID. The wiki says how to invite the bot to your server, you don't specify it in the config (since you have to manually drag the bot in).

**Comment by Aaronstar-McClure** [comment]
Still does not work. Do i need to do something with the link command?
