### ISSUE TITLE
Server console commands showing in Discord chat

### ISSUE THREAD

**Issue by jc2xs** [MiraWaNeko/DiscordIntegration#73]
Minecraft version: 1.12
DiscordIntegration version: 3.0.0

Expected behavior:  Server commands typed in the console shouldn't showing up in discord chat.  This didn't happen in 2.1.0

Actual behavior:  Server console commands are showing in discord chat

Example of 2.10 DiscordIntegration - This is what it should look like
    <Server> SERVER REBOOT in 5 minutes...
    <Server> SERVER SHUTTING DOWN IN 10 SECONDS. Saving map...
    Server shutdown
    Server started

Example of 3.0.0 DiscordIntegration - This shouldn't have the lines with "[Server] executed"
    [Server] SERVER REBOOT in 5 minutes...
    [Server] executed say SERVER REBOOT in 5 minutes...
    [Server] SERVER SHUTTING DOWN IN 10 SECONDS. Saving map...
    [Server] executed say SERVER SHUTTING DOWN IN 10 SECONDS. Saving map...
    [Server] executed save-all 
    [Server] executed stop 
    Server stopped!
    Server started!

**Comment by MiraWaNeko** [comment]
That is intended behavior.
Disable `relayCommands` to disable messages about command executions.

**Comment by jc2xs** [comment]
That worked!  Thanks for the advise!  I appreciate it.
