### ISSUE TITLE
Crash on Boot

### ISSUE THREAD

**Issue by C0LiSii0N** [MiraWaNeko/DiscordIntegration#74]
### Base informations
**Minecraft version:**
Forge 1.7.10 Build 1614 (Latest)

**DiscordIntegration version:**
1.7.10 V3

**Link to pastebin with (censored) config:** *Optional*
discordintegration.json: https://pastebin.com/tUKnjujz
fml-server-latest.log: https://pastebin.com/88Ty0sn0

When I launch the server it crash right after the "Done" message.  I looked in the previous issues and nothing work for me.

**Comment by MiraWaNeko** [comment]
Fixed in 3.0.1
