### ISSUE TITLE
Still having issues with custom commands that use arguments

### ISSUE THREAD

**Issue by jc2xs** [MiraWaNeko/DiscordIntegration#75]
Minecraft version: 1.12.1 Pack is ATM3
DiscordIntegration version:  3.0.1
Config:  https://pastebin.com/qPKZnDj6

I'm sure I'm just missing something in the config.  But I can't get the whitelist command to work.  The other command like tps and online work fine.  But those are open to everyone and don't use args.  So I'm not sure if this issue is with the permissions or that I've got something wrong in the args/command string.

I've also tried changing some of the role to IDs like this
          {
            "name": "whitelist",
            "command": "whitelist %args%",
            "enabled": true,
            "aliases": [],
            "permissions": [
              "role:owner",
              "role:302635636870086657",
              "role:264932313828163595"
            ]
          }

**Comment by grandrolf** [comment]
Change:
"command": "whitelist %args%",
to
"command": "whitelist {ARGS}",

And see if that works for you

**Comment by jc2xs** [comment]
Thank you @grandrolf that worked!  Very Cool!
