### ISSUE TITLE
Color Codes bug

### ISSUE THREAD

**Issue by C0LiSii0N** [MiraWaNeko/DiscordIntegration#77]
### Base informations
**Minecraft version:**
1.7.10
**DiscordIntegration version:**
3.0.1
**Link to pastebin with (censored) config:** *Optional*
"messages": {
          "chatMessage": "[§5Discord§f]{USER}> {MESSAGE}"
        },

I used version 2.1.0 and the color code was pasted normally but now it put the color but also "Â" where the § is.

**Comment by C0LiSii0N** [comment]
*When i put it in discord everything is good(No "Â")*

**Comment by Tencao** [comment]
Would like to second this, 1.11.2

**Comment by MiraWaNeko** [comment]
Make sure you're saving the config file in UTF-8 encoding.
Could you check if this fixes it?

**Comment by Tencao** [comment]
The file was default, and I was saving it as the same type using sublime 3. I'll double check the UTF-8 Encoding but honestly I would try to change or convert the & symbol to § automatically, as a large majority of mods use & for color codes due to issues like this.

**Comment by Tencao** [comment]
Tried to force save this as UTF-8 with subline, however the bug persists
