### ISSUE TITLE
Dynmap integration only working one direction

### ISSUE THREAD

**Issue by redsgreens** [MiraWaNeko/DiscordIntegration#80]
### Base informations
**Minecraft version:** 1.8.9

**DiscordIntegration version:** 3.0.1
**Dynmap version:** Dynmap-2.3-alpha-2-forge-1.8.9.jar

**Link to pastebin with (censored) config:** https://pastebin.com/ZBBDcz2M

### Actual behavior: Messages from Dynmap were visible in Discord, but Discord messages were not relayed to Dynmap.

**Comment by MiraWaNeko** [comment]
Derp, I forgot the other direction >_>
