### ISSUE TITLE
Joining/Leaving game not relayed

### ISSUE THREAD

**Issue by squirrelkiller** [MiraWaNeko/DiscordIntegration#85]
### Base informations
**Minecraft version:**
1.7.10
**DiscordIntegration version:**
3.0.2
**Link to pastebin with (censored) config:** *Optional*
https://pastebin.com/zKZSk2AY

### Expected behavior
When player joins/leaves it relays that to the discord server.

### Actual behavior
Player joining/leaving is silent on discord server. All other messages work

### Steps to reproduce
Install mod, join MC server, do not see join notice in discord server.

**Comment by grandrolf** [comment]
@squirrelkiller - question for you: line 37 - are you using brackets around the channel?
like this:
"discordChannel": [xxxxxxxxxxxxxxxxxx],

**Comment by squirrelkiller** [comment]
Sorry just returned from being away for a time. @grandrolf Yes I have tried it with and without brackets, Neither worked. I do believe I settled on with for some reason though.

**Comment by Shadou81** [comment]
Can confirm this issue; my server has the same problem. Everything else relays fine, but player joins and leaves are silent. Same MC version, same DiscordIntegration build.

**Comment by MiraWaNeko** [comment]
Found the issue - will be fixed in 3.0.4
