### ISSUE TITLE
Ignore commands?

### ISSUE THREAD

**Issue by ghost** [MiraWaNeko/DiscordIntegration#86]
### Base informations
**Minecraft version:** 1.12.1

**DiscordIntegration version:** mc1.12-3.0.2

Can there be a way to ignore certain commands? For example, when there's no chatting, discord channel is filled with: **[Server]** executed **list**

For now I have command relay disabled, but this is less than ideal.

Thank you!

**Comment by utoc** [comment]
I'd like to see this as well, especially for ignoring RCON commands which I use every 5 minutes to record memory usage.  Thanks so much!

**Comment by ProsperCraft** [comment]
I was shocked to see my console commands showing up in discord :)  +1 for me too.

**Comment by Ricket** [comment]
Prosper note you can disable commands from showing with a config. This bug is just requesting that you can disable *certain* commands from showing.

**Comment by Mijago** [comment]
I see the following possibilities:
* Using messageIgnoreRegex to also work with command messages
* Adding a command Blacklist/whitelist (like imc.mode)
