### ISSUE TITLE
config file not generating

### ISSUE THREAD

**Issue by topher2010** [MiraWaNeko/DiscordIntegration#88]
### Base informations
**Minecraft version:**
1.12.1

**DiscordIntegration version:**
3.0.2

**Link to pastebin with (censored) config:** *Optional*

### Expected behavior
Config file to be generated

### Actual behavior
No config file generated when I add it to the FTB Unstable 1.12.1 version 2.0.4 modpack

### Steps to reproduce
I installed the FTB Unstable 1.12.1 version 2.0.4, added the DiscordIntegration mod to the mods folder, started the modpack.  No config file is generated.

**Comment by Twonkk** [comment]
same issue on 1.10.2 using Space Astronomy 2 mod pack.

**Comment by IchigoGames** [comment]
same issues in 1.12.2

**Comment by IchigoGames** [comment]
derp nvm who would ever thing the config is named Chikachi lol
