### ISSUE TITLE
Discord Bot Not Showing.

### ISSUE THREAD

**Issue by DeCypherCR** [MiraWaNeko/DiscordIntegration#89]
### Base informations
**Minecraft version:**
1.10.2

**DiscordIntegration version:**
DiscordIntegration-mc1.10.2-3.0.2.jar

**Link to pastebin with (censored) config:** *Optional*

### Expected behavior
Discord Bot showed appear on our Discord.

### Actual behavior
Bot isn't showing up on our Discord, yet, it is there under the Roles of our Discord.

### Steps to reproduce
I followed the steps here:
https://github.com/Chikachi/DiscordIntegration/wiki/How-to-get-a-token-and-channel-ID-for-Discord

Have added the token and server id's to the config. Everything seems fine config side, it's just not adding Bot to our Discord.

**Comment by Ricket** [comment]
This doesn't sound like a mod issue, the mod doesn't put the bot in your discord. Follow the steps under "Add your new Discord bot user to your Discord server/guild" on the guide you linked.
