### ISSUE TITLE
Small Issues with Commands & Mentions & Console Spam

### ISSUE THREAD

**Issue by Inrixia** [MiraWaNeko/DiscordIntegration#92]
### Base informations
**Minecraft version:**
1.7.10 & 1.10+

**DiscordIntegration version:**
3.0.2

**Link to pastebin with (censored) config:** *Optional*
https://pastebin.com/2Q0HFSRF

### Expected behavior
!online and !tps Show results in Discord.
Join/Leave Messages showup.
Mentions to roles work.

### Actual behavior
**Minecraft 1.7.10 Only :**
Join/Leave messages do not display in discord. No error message. (Maybe a duplicate of: https://github.com/Chikachi/DiscordIntegration/issues/85)

Messages to minecraft are duplicated in (console only) 5x+ times. You can see in this image:
(Note the server on the right is 1.10 and the left is 1.7.10)
[![Screenshot from Gyazo](https://gyazo.com/79bc25796ac670163cbfa0cb33674a53/raw)](https://gyazo.com/79bc25796ac670163cbfa0cb33674a53)

Online and TPS commands do not display and can cause errors in minecraft console... Also does not work with a custom /list command. A custom /list command will work in minecraft though, and /discord online shows online people in console. It just does not forward to discord.
Console Error: https://pastebin.com/zxRrg42B

Also custom commands like !give don't work and give the same error as above. But !tp works fine.

**Minecraft 1.10+ & 1.7.10 [Maybe More Versions]**
Mentions to roles eg **@Mod** or **@Admins** dont work and give the id instead.
EG: **@Mod** gives: <Inrix> **<@78046497789181954>** in discord.

### Steps to reproduce
Run my configs and Join/Leave/!online/!tps/Mention a Role.

Note: All servers are using the exact same config.

**Comment by Inrixia** [comment]
@Chikachi Any ETA on a fix? Not being able to see people Join/Leave or !online is really disabling :)

**Comment by MiraWaNeko** [comment]
Sadly I don't have any ETA yet, as there have been a lot of issue reports lately and work have been busy.
