### ISSUE TITLE
Sometimes Discord connection is silently lost

### ISSUE THREAD

**Issue by Ricket** [MiraWaNeko/DiscordIntegration#93]
### Base informations
**Minecraft version:** 1.10.2

**DiscordIntegration version:** DiscordIntegration-mc1.10.2-3.0.2.jar

**Link to pastebin with (censored) config:** *Optional*

### Expected behavior
All expected messages (login, logout, chat, etc) make it to discord.

### Actual behavior
Over the past week, we have had a couple times where the bot is not relaying the usual messages. Earlier in the week it just plain stopped for around 24 hours, nothing made it to discord - logins, logouts, chat messages, none of it. I tried to find a command to make it reauthenticate or something but it looks like there was one that was removed long ago. It magically resolved itself later, without any server restart.

Yesterday it was fine, I played a good portion of the day and it dutifully relayed all logins, logouts, achievements etc. Today, it missed a login message, so the user alerted me that the mod was screwing up again, and so I ran "/list" on the server console but we got the message in discord about executing that command. And then chat continued to be relayed both directions. So I guess it just missed the login message this time.

### Steps to reproduce
Not sure.

What other info can I send, is there a way of enabling trace logging? There's no log messages related to discord in the fml-server-latest.log or the console.

**Comment by MiraWaNeko** [comment]
This could be caused by Discord updating.

Hopefully 3.0.3 have fixed this as I have updated JDA (the library used by DiscordIntegration for communications with Discord). JDA is also automatically trying to reconnect in case it loses connection to Discord.
Messages about this should be logging.

**Comment by Ricket** [comment]
Thanks, fingers crossed, I just updated our server to 3.0.3 and will let you know if I see the issue again.
