### ISSUE TITLE
Bot will not go online in Discord

### ISSUE THREAD

**Issue by Shadou81** [MiraWaNeko/DiscordIntegration#94]
### Base informations
**Minecraft version: 1.7.10

**DiscordIntegration version: 3.0.3

**Link to pastebin with (censored) config: https://hastebin.com/yesevohamo.json

### Expected behavior
Discord bot goes live and begins relaying messages to and from the server

### Actual behavior
Discord bot remains offline

### Steps to reproduce
I have followed the steps on https://github.com/Chikachi/DiscordIntegration/wiki/How-to-get-a-token-and-channel-ID-for-Discord to get the token ID and the channel ID to add to the config, and created the bot user on the discord and added it to the server. The bot is showing up in the userlist, but never goes online when the server is live. 

I have double checked the token. I have double checked the channel. I had to go digging through the issues here in the github to learn that I needed to create a webhook for the bot as well. I've regenerated the config and reentered the information multiple times. I've checked, double checked, and triple checked the token ID (and yes, I'm aware it changes every time you pull it, I've updated the config every time). 

I'm out of ideas. This isn't working.

EDIT: I've found and fixed a small issue in the config (missing comma). Now it crashes the server. 
Logged events: https://hastebin.com/isegulepic.rb

**Comment by Inrixia** [comment]
This is covered in https://github.com/Chikachi/DiscordIntegration/issues/91 Read the most recent comments at the bottom. Version 3.0.2 works fine excluding some issues which you can find in the issue https://github.com/Chikachi/DiscordIntegration/issues/91 and https://github.com/Chikachi/DiscordIntegration/issues/92
