### ISSUE TITLE
Commands not working on all servers [Identical Configs]

### ISSUE THREAD

**Issue by Inrixia** [MiraWaNeko/DiscordIntegration#95]
### Base informations
**Minecraft version:**
1.7.10

**DiscordIntegration version:**
3.0.4

**Link to pastebin with (censored) config:** *Optional*
Divine Journey Config: https://pastebin.com/1WpPmhHN
FTB Infinity Config: https://pastebin.com/bYTG6evg

### Expected behavior
Commands work fine.

### Actual behavior
No matter what permissions/role-id's are set for commands they will not work for some servers. What is confusing is that even with identical configs, the same issue appears. Both servers are running identical discordintegration versions and identical configs excluding the bots... (I'm gonna look into if its a bot issue now but I don't think it should be).

Here you can see what I'm talking about with commands only working on some of the servers. Note all configs are identical excluding the bot's token.

[![Screenshot from Gyazo](https://gyazo.com/49bb550bf3181e2614de669630202400/raw)](https://gyazo.com/49bb550bf3181e2614de669630202400)

### Steps to reproduce
Use the above configs on Divine Journey and FTB Infinity and try use commands on both.

**Comment by Inrixia** [comment]
Found the issue! We were running Forge Essentials on some servers and it seems to be breaking some permissions... For now removing Forge Essentials seems to fix it but we are looking into other methods. Dunno if this is something you want to put on the back burner @Chikachi

**Comment by MiraWaNeko** [comment]
You need to add permissions to DiscordIntegration.

Just use `DiscordFakeUser` as username or `828653ca-0185-43d4-b26d-620a7f016be6` as UUID.
https://mcuuid.net/?q=828653ca-0185-43d4-b26d-620a7f016be6

**Comment by MiraWaNeko** [comment]
Just to also write it in here.
You can use `/op DiscordFakeUser` to make the mod's command sender an OP.
