### ISSUE TITLE
Bots still not working with 3.0.4 on 1.7.10 

### ISSUE THREAD

**Issue by wolfhound871** [MiraWaNeko/DiscordIntegration#96]
https://puu.sh/xSHnv/6b000ad40b.png what did i do wrong cause they cant see anyone type from discord  and players say they cant see the other server talking in game nothing has changed from 2.1.0  both servers cant see messages and discord cant type into game still

problem cant talk to players in game from discord and minecraft servers cant see each other talking 

expected behavior to be able to talk to in game players from discord and to see other servers talking in game 
config : https://pastebin.com/2wcqvs0C
also i am using dividers or organizers in my discord what ever they are called they are what originally broke it from the discord update just so you are testing it with them also

**Comment by Inrixia** [comment]
Comparing your config to mine... (https://pastebin.com/2Q0HFSRF)

You don't have a channel specified under channels on line 19 of your config.

Comparison for reference: [![Screenshot from Gyazo](https://gyazo.com/ce93112b6b467f26e94a509740fbedd2/raw)](https://gyazo.com/ce93112b6b467f26e94a509740fbedd2)

**Comment by wolfhound871** [comment]
isnt that just for commands and stuff i added it so we will see when my servers do there restart in a few 
https://puu.sh/xSK9n/7e3622c416.png

**Comment by Electrofried** [comment]
no, since 3.0 the configs changed. Also, you can just do /discord config reload to reload the configs while the server is running

**Comment by wolfhound871** [comment]
@Electrofried  i did that just now i figured it out but no change will wait till server restarts

**Comment by wolfhound871** [comment]
log says there is something wrong with the config https://pastebin.com/eqSEg6yQ
[3.0.4] Config had invalid syntax - Please check it using a JSON tool ( https://jsonlint.com/ ) or make sure it have the right content
[22:49:36] [Server thread/WARN]: com.google.gson.JsonSyntaxException: java.io.EOFException: End of input at line 86 column 2

**Comment by wolfhound871** [comment]
config is broken now
no idea what i did

**Comment by MiraWaNeko** [comment]
You forgot to close the object.
On line 20 add a `}` like this `"267854909938860035": {}`

**Comment by wolfhound871** [comment]
i also forgot to close with } back to the main margin fixed that with it telling me what line though

**Comment by wolfhound871** [comment]
you can close this its fixed thx to all that helped
