### ISSUE TITLE
No permissions for commands

### ISSUE THREAD

**Issue by Velikss** [MiraWaNeko/DiscordIntegration#97]
### Base informations
**Minecraft version: 1.7.10**

**DiscordIntegration version: 3.0.4**

**Link to pastebin with (censored) config:** *https://pastebin.com/0JKwJPbf*

### Expected behavior
Being able to send commands on discord and get a response.
### Actual behavior
Any command thats entered will be denied by the bot.
### Steps to reproduce
Set everything up as described on the wiki.

**Comment by Velikss** [comment]
It might be connected with ForgeEssentials, like in #95.
FE doesn't know the user nor the uuid you posted there, so there is no way of giving it the right permissions.

**Comment by MiraWaNeko** [comment]
Sounds like it's not looking up the UUID or player...

**Comment by Velikss** [comment]
`/op DiscordFakeUser` seems like it did the trick. The commands work fine now. Also manually adding the UUID and username to the permissions file worked aswell. 
I'm curious though, I never had to do this before in previous versions? Is that right?

**Comment by MiraWaNeko** [comment]
Oh right, you can just OP it.

Yes, that's right.
DiscordFakeUser is a Minecraft account I bought and will never use for anything else than in this mod.
That way I'm sure the UUID will never be randomly taken by another Minecraft account.
