### ISSUE TITLE
[1.10.2] [mod 3.0.4] Chat is seen in Discord but not in game

### ISSUE THREAD

**Issue by Sora-Canstavia** [MiraWaNeko/DiscordIntegration#98]
### Base informations
**Minecraft version:**
Minecraft Version 1.10.2
**DiscordIntegration version:**
DiscordIntegration 3.0.4
**Link to pastebin with (censored) config:** *Optional*
https://pastebin.com/eHNZ5H0u Please note I Have replaced the token and channel ID with "-----"

### Expected behavior
For chat messages to send and receive both in game and in Discord
### Actual behavior
Chat messages received in Discord but not in game
### Steps to reproduce
Install the mod and run server.

**Comment by MiraWaNeko** [comment]
In the config, add the channel to the channels object under discord.

**Comment by Sora-Canstavia** [comment]
Ok, I Tried adding it in each channels object under discord, one at a time, no matter where I Put the channel ID there it would cause the mod to fail to load. I tried putting it before the {} brackets and in the brackets, but when I Put it inside the brackets the text editor I Use on my server showed that it was invalid code.
